variables:
  OUTPUT: thesis-printable
  TEXMFHOME: ./texmf/

pdf:
  stage: build
  # image: git.kpi.fei.tuke.sk:4567/kpi/latex
  image: bletvaska/thesis:latest
  # Documentation for LaTex docker image: https://git.kpi.fei.tuke.sk/kpi/latex
  script:
    # - latexmk -pdf -interaction=nonstopmode $MAIN_TEX_FILE
    - make --makefile=/app/Makefile printable
  artifacts:
    paths:
      - "dist/${OUTPUT}.pdf"
    expire_in: 2 days
  only:
    - master
