# Documentation for LaTex docker image: https://git.kpi.fei.tuke.sk/kpi/latex
image: git.kpi.fei.tuke.sk:4567/kpi/latex:2025.09.1

stages:
  - build

default:
  interruptible: true
  artifacts:
    paths:
      - dist/
    expire_in: 7 days

pdf:
  stage: build
  script:
    - make --makefile=/app/Makefile printable thesis
  only:
    - master

diff:
  stage: build
  allow_failure: true
  script:
    - make --makefile=/app/Makefile diff
  artifacts:
    when: always
  only:
    - master
