variables:
  OUTPUT: thesis
  TEXMFHOME: ./texmf/

stages:
  - build

printable:
  stage: build
  # image: git.kpi.fei.tuke.sk:4567/kpi/latex
  image: bletvaska/thesis:latest
  # Documentation for LaTex docker image: https://git.kpi.fei.tuke.sk/kpi/latex
  script:
    # - latexmk -pdf -interaction=nonstopmode $MAIN_TEX_FILE
    - make --makefile=/app/Makefile printable
    - mv dist/*pdf .
  artifacts:
    paths:
      - "${OUTPUT}-printable.pdf"
    expire_in: 2 days
  only:
    - master

ebook:
  stage: build
  # image: git.kpi.fei.tuke.sk:4567/kpi/latex
  image: bletvaska/thesis:latest
  # Documentation for LaTex docker image: https://git.kpi.fei.tuke.sk/kpi/latex
  script:
    # - latexmk -pdf -interaction=nonstopmode $MAIN_TEX_FILE
    - make --makefile=/app/Makefile ebook
    - mv dist/*pdf .
  artifacts:
    paths:
      - "${OUTPUT}-ebook.pdf"
    expire_in: 2 days
  only:
    - master
